#!/usr/bin/env bash
set -euo pipefail
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:${PATH:-}"

if [[ $# -lt 1 ]]; then
  echo "usage: $0 <task_dir>"
  exit 2
fi

TASK_DIR="$1"
META="$TASK_DIR/meta.json"
if [[ ! -f "$META" ]]; then
  echo "meta.json missing: $META"
  exit 1
fi

TASK_ID="$(jq -r '.id' "$META")"
STRATEGY="$TASK_DIR/${TASK_ID}.strategy.json"
if [[ ! -f "$STRATEGY" ]]; then
  echo "strategy missing: $STRATEGY"
  exit 1
fi

GOAL="$(jq -r '.goal // ""' "$STRATEGY")"
GOAL_LOWER="$(printf '%s' "$GOAL" | tr '[:upper:]' '[:lower:]')"

DELIVERY_DIR="$TASK_DIR/delivery"
mkdir -p "$DELIVERY_DIR"

WS_MAIN="$DELIVERY_DIR/websocket_calculator.py"
WS_TEST="$DELIVERY_DIR/test_websocket_calculator.py"
RUNBOOK_MD="$DELIVERY_DIR/RUNBOOK.md"
LATEST_AMENDMENT="$(jq -r '.latest_requirement_amendment // ""' "$META" 2>/dev/null || true)"

is_websocket_calculator_goal() {
  [[ "$GOAL_LOWER" == *"websocket"* || "$GOAL_LOWER" == *"web socket"* || "$GOAL_LOWER" == *"ws"* || "$GOAL" == *"websocket"* || "$GOAL" == *"WebSocket"* ]] \
    && [[ "$GOAL_LOWER" == *"calc"* || "$GOAL_LOWER" == *"calculator"* || "$GOAL" == *"计算器"* ]]
}

append_worker_evidence() {
  local action="$1"
  local changed="$2"
  {
    echo "- Latest action: $action"
    echo "- Changed files: $changed"
    echo "- Evidence: deterministic implementation generated by worker_realize_task.sh"
    if [[ -n "$LATEST_AMENDMENT" ]]; then
      echo "- Amendment applied: $LATEST_AMENDMENT"
    fi
  } >> "$TASK_DIR/work.md"
}

append_test_command() {
  local cmd="$1"
  if ! grep -Fq "$cmd" "$TASK_DIR/test.md" 2>/dev/null; then
    {
      echo "- Commands: $cmd"
      echo "- Evidence: unit test command prepared by worker"
    } >> "$TASK_DIR/test.md"
  fi
}

if is_websocket_calculator_goal; then
  cat > "$WS_MAIN" <<'PY'
"""Async WebSocket calculator core with safe expression evaluation.

Server runtime is optional: if `websockets` is installed, run `python websocket_calculator.py`.
Core logic (`evaluate_expression`, `process_message`) has no third-party dependency.
"""

from __future__ import annotations

import ast
import json
from typing import Any


_ALLOWED_BINOPS = {
    ast.Add: lambda a, b: a + b,
    ast.Sub: lambda a, b: a - b,
    ast.Mult: lambda a, b: a * b,
    ast.Div: lambda a, b: a / b,
    ast.Mod: lambda a, b: a % b,
    ast.Pow: lambda a, b: a ** b,
}
_ALLOWED_UNARY = {
    ast.UAdd: lambda a: +a,
    ast.USub: lambda a: -a,
}


def _eval(node: ast.AST) -> float:
    if isinstance(node, ast.Expression):
        return _eval(node.body)
    if isinstance(node, ast.Constant) and isinstance(node.value, (int, float)):
        return float(node.value)
    if isinstance(node, ast.BinOp) and type(node.op) in _ALLOWED_BINOPS:
        left = _eval(node.left)
        right = _eval(node.right)
        return float(_ALLOWED_BINOPS[type(node.op)](left, right))
    if isinstance(node, ast.UnaryOp) and type(node.op) in _ALLOWED_UNARY:
        return float(_ALLOWED_UNARY[type(node.op)](_eval(node.operand)))
    raise ValueError("unsupported expression")


def evaluate_expression(expr: str) -> float:
    parsed = ast.parse(expr, mode="eval")
    return _eval(parsed)


def process_message(raw: str) -> str:
    try:
        payload: Any = json.loads(raw)
        expr = str(payload.get("expression", "")).strip()
        if not expr:
            raise ValueError("missing expression")
        result = evaluate_expression(expr)
        return json.dumps({"ok": True, "result": result})
    except Exception as exc:  # noqa: BLE001
        return json.dumps({"ok": False, "error": str(exc)})


async def serve(host: str = "127.0.0.1", port: int = 8765) -> None:
    try:
        import websockets  # type: ignore
    except Exception as exc:  # noqa: BLE001
        raise RuntimeError("websockets package not installed") from exc

    async def handler(websocket):
        async for message in websocket:
            await websocket.send(process_message(message))

    async with websockets.serve(handler, host, port):
        print(f"websocket calculator listening on ws://{host}:{port}")
        await websockets.Future()


if __name__ == "__main__":
    import asyncio

    asyncio.run(serve())
PY

  cat > "$WS_TEST" <<'PY'
import json
import unittest

from websocket_calculator import evaluate_expression, process_message


class WebSocketCalculatorTests(unittest.TestCase):
    def test_eval_expression(self):
        self.assertEqual(evaluate_expression("1+2*3"), 7.0)

    def test_process_message_ok(self):
        res = json.loads(process_message('{"expression":"(2+3)*4"}'))
        self.assertTrue(res["ok"])
        self.assertEqual(res["result"], 20.0)

    def test_process_message_error(self):
        res = json.loads(process_message('{"expression":"import os"}'))
        self.assertFalse(res["ok"])
        self.assertIn("error", res)
        self.assertTrue(len(str(res["error"])) > 0)


if __name__ == "__main__":
    unittest.main()
PY

  cat > "$RUNBOOK_MD" <<'MD'
# WebSocket Calculator Runbook

## Run
1. `cd delivery`
2. Optional dependency install: `python3 -m pip install websockets`
3. Start server: `python3 websocket_calculator.py`
4. Unit tests: `python3 -m unittest -q`

## Notes
- Core calculator logic is dependency-free and covered by unit tests.
- Runtime server requires `websockets` package.
MD

  append_worker_evidence "implemented websocket calculator core and tests" "delivery/websocket_calculator.py, delivery/test_websocket_calculator.py, delivery/RUNBOOK.md"
  append_test_command "cd delivery && python3 -m unittest -q"
  echo "worker delivered websocket-calculator task: $TASK_ID"
  exit 0
fi

{
  echo "- Latest action: worker could not map goal to deterministic template"
  echo "- Changed files: none"
  echo "- Blockers: unsupported goal for worker_realize_task.sh"
} >> "$TASK_DIR/work.md"
echo "unsupported goal for deterministic worker: $GOAL"
exit 1
